### ISSUE TITLE
Use winston as middleware

### ISSUE THREAD

**Issue by amitaibu** [shoov/shoov-nodejs#19]
See code examples [here](https://cloud.google.com/nodejs/getting-started/logging-application-events)

**Comment by solker** [comment]
Ops, found [`debug`](https://www.npmjs.com/package/debug) module in `bin/www` that use same env variable `DEBUG`. Guess need to rename `debug` env in `routes/ci.js`. Or stop using debug and save only `winston`. Also I see `morgan` logger in logs :)

![image](https://cloud.githubusercontent.com/assets/10127295/8511099/1f9feb62-2311-11e5-8496-860e64a7defb.png)
