### ISSUE TITLE
New abstract layer for .shoov.yml

### ISSUE THREAD

**Issue by solker** [shoov/shoov-nodejs#24]
We need realize abstract layer to parse and use .shoov.yml in node js backend and in php-ci.
I think for node js it should be module. Which should realize next functions:
* parse .shoov.yml and handle all errors. (object is empty, object not contain script directive or any other important fields, auth env, etc...)
* functions like getAddons, getUsername, getPassword, getScript and etc...

**Comment by amitaibu** [comment]
Closing for now.
