### ISSUE TITLE
Investigate the elevated error rates from curl after adding selenium

### ISSUE THREAD

**Issue by amitaibu** [shoov/shoov-nodejs#30]
`cURL error 28: Resolving timed out after 30545 milliseconds (GuzzleHttp\Exception\ConnectException)`

```
Examples:
| url | text | author |
| content/automatic-qa/ | Here is a known fact | Amitai Burstein |
l cURL error 28: Resolving timed out after 30545 milliseconds (GuzzleHttp\Exception\ConnectException)
| content/phantomcss-ui-regression/ | What's fun about having | Amitai Burstein |
| content/backend-free-apps-grunt-jekyll-d3js/ | When we started working | Carlos Mantilla |
```

@solker lets discuss this

**Comment by solker** [comment]
@amitaibu what you mean? Which behat tests are failed?

**Comment by amitaibu** [comment]
btw, another error I've seen already, even since the selenium deploy is `cURL error 6: Could not resolve host: gizra.com`

**Comment by solker** [comment]
Our office have two internet connections, HOT and Cellcom. 
When flow going throw cellcom it is crash.
```
root@982e08f62b52:/# mtr -rw www.gizra.com
Start: Sun Jun 28 11:15:15 2015
HOST: 982e08f62b52 Loss%   Snt   Last   Avg  Best  Wrst StDev
  1.|-- 172.17.42.1   0.0%    10    0.1   0.1   0.1   0.1   0.0
  2.|-- 192.168.1.1   0.0%    10    0.5   0.4   0.4   0.5   0.0
  3.|-- 10.0.0.138    0.0%    10    1.3   1.3   1.2   1.5   0.0
  4.|-- ???          100.0    10    0.0   0.0   0.0   0.0   0.0
root@982e08f62b52:/# mtr -rw www.gizra.com
Start: Sun Jun 28 11:15:31 2015
HOST: 982e08f62b52                            Loss%   Snt   Last   Avg  Best  Wrst StDev
  1.|-- 172.17.42.1                              0.0%    10    0.1   0.1   0.1   0.1   0.0
  2.|-- 192.168.1.1                              0.0%    10    0.4   0.4   0.4   0.5   0.0
  3.|-- 10.0.0.1                                 0.0%    10    0.6   4.2   0.6  36.1  11.2
  4.|-- 10.226.160.1                             0.0%    10    9.9  15.9   9.9  49.0  11.7
  5.|-- bzq-114-65-46.cust.bezeqint.net          0.0%    10   11.8  13.8   8.7  23.3   4.3
  6.|-- bzq-114-65-45.cust.bezeqint.net          0.0%    10    9.8  18.0   9.8  43.2   9.7
  7.|-- bzq-219-189-197.cablep.bezeqint.net      0.0%    10   12.6  13.3   9.5  25.7   5.4
  8.|-- bzq-219-189-169.cablep.bezeqint.net      0.0%    10   15.1  14.4   8.3  31.9   7.2
  9.|-- bzq-219-189-205.dsl.bezeqint.net         0.0%    10   16.4  21.8   9.1  65.3  17.1
 10.|-- bzq-219-189-90.cablep.bezeqint.net       0.0%    10   17.4  16.6  10.9  33.5   6.7
 11.|-- 213.242.116.129                          0.0%    10   47.0  55.3  47.0  67.6   7.6
 12.|-- ae-127-3513.edge6.Amsterdam1.Level3.net  0.0%    10   74.8  72.2  68.3  82.4   5.0
 13.|-- ???                                     100.0    10    0.0   0.0   0.0   0.0   0.0
 14.|-- 23.235.43.133                           10.0%    10   74.9  74.3  69.2  91.3   6.5
```

How I am determine  where is which connection?
Cellcom connection have the gateway 10.0.0.138.
Hot connection have the gateway 10.0.0.1.
I got this information from our router.

**Comment by solker** [comment]
I have tested without Cellcom interface but still have the issue.

**Comment by solker** [comment]
Very interesting but on Cellcom connection errors almost left.

**Comment by solker** [comment]
Well network can not be 100% work. It is solution:
`curl --connect-timeout 8 --max-time 60 --retry 3 --retry-delay 3 http://www.gizra.com/content/automatic-qa/`

It is mean:
`--connect-timeout 8` maximum time to try to connect to host. 8 seconds equal to 3 TCP Retransmission packages on 1,3,7 seconds. 
`--max-time 60` common time for all curl work. 
`--retry 3` mean try to connect to host three times. 
`--retry-delay 3` make delay between tries to 3 seconds. 

I think it give to us 90% guaranty of status of host.

**Comment by solker** [comment]
So sad but PHP curl not supporting --retry and --retry-delay 3 options.

**Comment by solker** [comment]
I can't understand which component send requests to a site from behat feature. In my case this work doing Symfony request. Why not a silenium2 or phantomjs? Which driver we use on the production?

**Comment by amitaibu** [comment]
Update: I have set 15 sec for [sleep](https://github.com/shoov/shoov/pull/78/files#diff-c6d95ddbaab26825365766cd18fc280aR73) (via variable) between each build item, and so far it seems error rate has been reduced. I'll keep monitoring.

**Comment by amitaibu** [comment]
Update: No errors in the past 2 hours, so it seems we were able to find a temp solution.

**Comment by amitaibu** [comment]
Update: First error - `cURL error 56: Recv failure: Connection reset by peer (GuzzleHttp\Exception\RequestException)`
